### ISSUE TITLE
Embed with TinyMCE does not work

### ISSUE THREAD

**Issue by ebbertd** [Opencast-Moodle/moodle-filter_opencast#29]
When using the TinyMCE editor, the filter does not work. Instead of the player only a link to the player is added.

**Comment by justusdieckmann** [comment]
This is because the legacy tinyMCE editor "embeds" videos via `<a>` tags. The new tinyMCE editor lets the user choose whether to add a link or video or audio element, just like the atto editor.

So the missing support for the legacy tinyMCE editor might soon be not important anymore, but it might still be nice to filter matching `<a>` links, since it eliminates potential user errors (not clicking the `video` tab when embedding a video)
