### ISSUE TITLE
Reduce data sent via lti

### ISSUE THREAD

**Issue by tobiasreischmann** [Opencast-Moodle/moodle-filter_opencast#9]
In the end, it could be possible that someone wants to use our plugin so connect to a third-party opencast instance. We should think about, what data is actually necessary to be sent via lti to achieve authentication. Do we really need for instance the full name of the user?

https://github.com/TamaraGunkel/moodle-filter_opencastfilter/blob/abed94061cd2042d0814606e01f7d766ef522456/lib.php#L50

**Comment by loewis** [comment]
The LTI specification says:

> lis_person_name_given=Jane
> lis_person_name_family=Public
> lis_person_name_full=Jane Q. Public
> lis_person_contact_email_primary=user@school.edu
> These fields contain information about the user account that is performing this launch.  The names of these data items are taken from LIS.  The precise meaning of the content in these fields is defined by LIS. These parameters are recommended unless they are suppressed because of privacy settings.

 So I would suggest to follow the spec and only suppress the data if there are privacy reasons (which should be in the realm of the Moodle administrator), not because you think the data are unnecessary.

For example, it might be desirable some day to send an email to the user when the workflow is finished. Without including the email address in the launch, Opencast might not be able to properly determine where to send the email.

**Comment by NinaHerrmann** [comment]
Currently, the request sends the information stated above. Therefore, this issue will be marked as solved.

**Comment by NinaHerrmann** [comment]
Very old Pull request #16 handles part of it but also deletes user mail etc. so it would require a review.

**Comment by TamaraGunkel** [comment]
As the next release won't use LTI anymore, I'm closing this issue.

**Comment by mastnym** [comment]
Hi, @TamaraGunkel can I ask why you dropped the LTI support? We use LTI for user authentication to Opencast and with the current filter plugin I'm unable to serve the video, cause there is no authentication request in the backkground implemented. Thanks
